name: Deploy UAT

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-deploy-uat:
    runs-on: ubuntu-latest
    environment: uat  # manual approval required here
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET 8 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'
      - run: dotnet restore
      - run: dotnet build --configuration Release
      - run: dotnet publish -c Release -o ./publish
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: blazor-app
          path: ./publish
      - name: Deploy to UAT
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_UAT }}
          publish-profile: ${{ secrets.AZURE_CREDENTIALS_UAT }}
          package: ./publish
