name: Deploy Production

on:
  workflow_run:
    workflows:
      - Deploy Test
      - Deploy UAT
    types:
      - completed

jobs:
  deploy-prod:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    environment: production  # manual approval required here
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: blazor-app
          path: ./publish
      - name: Deploy to Production
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_PROD }}
          publish-profile: ${{ secrets.AZURE_CREDENTIALS_PROD }}
          package: ./publish
